import type { RuntimeAppSnapshot } from './snapshot.js'

const now = '2026-05-16T03:00:00.000Z'

export const mockSnapshot: RuntimeAppSnapshot = {
  generated_at: now,
  dashboard: {
    generated_at: now,
    agent_summary: {
      idle: 2,
      busy: 4,
      offline: 0,
      error: 0,
      stale: 1,
    },
    pipeline: {
      total_projects: 3,
      active_projects: 3,
      by_lifecycle_state: {
        lead: 0,
        qualified: 0,
        proposal: 1,
        won: 0,
        discovery: 1,
        implementation: 1,
        qa: 0,
        delivered: 0,
        support: 0,
        closed: 0,
      },
    },
    approvals: {
      pending_count: 1,
      items: [
        {
          request_id: 'apr-delivery-001',
          gate: 'delivery_final',
          from_agent: 'engineering_agent',
          project_id: 'proj-acme-001',
          summary: 'Approve delivery package for ACME analytics runtime.',
          artifact_ref: 'projects/acme/proj-acme-001/deliverable-v1/',
          timestamp: now,
        },
      ],
    },
    handoffs: {
      awaiting_acknowledgment_count: 1,
      overdue_acknowledgment_count: 0,
    },
    delivery: {
      blocker_count: 1,
      support_ticket_count: 2,
    },
    kpis: {
      agent_utilization_rate: 0.57,
      active_project_count: 3,
      pending_approval_count: 1,
      support_ticket_count: 2,
    },
    refresh: {
      source: 'agent_registry_and_audit_log',
      audit_event_count: 18,
      communication_event_count: 12,
    },
    operational_issues: [
      {
        kind: 'project_blocker',
        severity: 'medium',
        summary: 'Waiting on client data export for ACME analytics runtime.',
        blocker_id: 'blocker-acme-export',
        project_id: 'proj-acme-001',
        owner_agent: 'project_manager_agent',
      },
    ],
    projects: [
      {
        project_id: 'proj-acme-001',
        client_id: 'acme',
        lifecycle_state: 'implementation',
        current_milestone: 'delivery_candidate_review',
        active_agent_ids: ['engineering-agent', 'project-manager-agent'],
        updated_at: now,
      },
      {
        project_id: 'proj-nova-002',
        client_id: 'nova',
        lifecycle_state: 'discovery',
        current_milestone: 'spec_finalization',
        active_agent_ids: ['product-agent'],
        updated_at: '2026-05-16T02:20:00.000Z',
      },
      {
        project_id: 'proj-orbit-003',
        client_id: 'orbit',
        lifecycle_state: 'proposal',
        current_milestone: 'commercial_review',
        active_agent_ids: ['sales-agent', 'marketing-agent'],
        updated_at: '2026-05-16T01:45:00.000Z',
      },
    ],
  },
  approvals: [
    {
      request_id: 'apr-delivery-001',
      gate: 'delivery_final',
      from_agent: 'engineering_agent',
      timestamp: now,
      project_id: 'proj-acme-001',
      summary: 'Approve delivery package for ACME analytics runtime.',
      recommendation: 'Approve after verifying client export blocker is cleared.',
      risks: ['Client export may arrive later than current delivery window.'],
      options: ['approve', 'reject', 'revise'],
      artifact_ref: 'projects/acme/proj-acme-001/deliverable-v1/',
    },
  ],
  jobs: [
    {
      job_id: 'job-report-001',
      kind: 'report_generate',
      status: 'running',
      attempts: 1,
      max_attempts: 3,
      detail: 'Generating operator digest.',
      worker_id: 'worker-ceo',
      scheduled_at: '2026-05-16T02:59:00.000Z',
      started_at: now,
    },
    {
      job_id: 'job-retry-001',
      kind: 'handoff_retry',
      status: 'failed',
      attempts: 2,
      max_attempts: 3,
      detail: 'Retry product to engineering handoff.',
      project_id: 'proj-nova-002',
      worker_id: 'worker-product',
      scheduled_at: '2026-05-16T02:30:00.000Z',
      started_at: '2026-05-16T02:30:05.000Z',
      finished_at: '2026-05-16T02:30:25.000Z',
      error: 'Receiver was temporarily busy.',
    },
  ],
  messages: [
    {
      log_id: 'msg-001',
      recorded_at: '2026-05-16T02:58:00.000Z',
      message: {
        from: 'product_agent',
        to: 'engineering_agent',
        message_type: 'discovery_handoff',
        project_id: 'proj-nova-002',
        timestamp: '2026-05-16T02:57:50.000Z',
        payload: {
          handoff_id: 'handoff-nova-discovery',
          spec_artifact_ref: 'projects/nova/proj-nova-002/spec.md',
          mvp_scope: ['Operator dashboard', 'Approval workflow'],
          tool_stack: ['Bun', 'Lit', 'Vite'],
          acceptance_criteria: ['Snapshot polling works'],
          technical_constraints: ['Local-first runtime only'],
          implementation_risks: ['Provider readiness can block e2e smoke'],
        },
      },
      status: 'rejected',
      rejection_reason: 'Engineering agent was busy.',
      requires_acknowledgment: true,
    },
  ],
  audit: [
    {
      timestamp: now,
      action: 'runtime_boot',
      actor: 'operator-ui',
      target: 'runtime-dev-01',
      detail: 'Runtime app state initialized.',
    },
    {
      timestamp: '2026-05-16T02:40:00.000Z',
      action: 'approval_requested',
      actor: 'engineering_agent',
      target: 'apr-delivery-001',
      detail: 'Delivery approval requested.',
    },
  ],
  projects: [
    {
      project_id: 'proj-acme-001',
      client_id: 'acme',
      lifecycle_state: 'implementation',
      current_milestone: 'delivery_candidate_review',
      active_agent_ids: ['engineering-agent', 'project-manager-agent'],
      updated_at: now,
    },
    {
      project_id: 'proj-nova-002',
      client_id: 'nova',
      lifecycle_state: 'discovery',
      current_milestone: 'spec_finalization',
      active_agent_ids: ['product-agent'],
      updated_at: '2026-05-16T02:20:00.000Z',
    },
    {
      project_id: 'proj-orbit-003',
      client_id: 'orbit',
      lifecycle_state: 'proposal',
      current_milestone: 'commercial_review',
      active_agent_ids: ['sales-agent', 'marketing-agent'],
      updated_at: '2026-05-16T01:45:00.000Z',
    },
  ],
  project_details: [
    {
      project: {
        project_id: 'proj-acme-001',
        client_id: 'acme',
        lifecycle_state: 'implementation',
        current_milestone: 'delivery_candidate_review',
        active_agent_ids: ['engineering-agent', 'project-manager-agent'],
        updated_at: now,
      },
      history: [
        {
          project_id: 'proj-acme-001',
          client_id: 'acme',
          lifecycle_state: 'discovery',
          active_agent_ids: ['product-agent'],
          current_milestone: 'requirements_locked',
          updated_at: '2026-05-15T09:00:00.000Z',
          recorded_at: '2026-05-15T09:00:00.000Z',
        },
        {
          project_id: 'proj-acme-001',
          client_id: 'acme',
          lifecycle_state: 'implementation',
          active_agent_ids: ['engineering-agent', 'project-manager-agent'],
          current_milestone: 'delivery_candidate_review',
          updated_at: now,
          recorded_at: now,
        },
      ],
      approvals: [
        {
          request_id: 'apr-delivery-001',
          gate: 'delivery_final',
          from_agent: 'engineering_agent',
          timestamp: now,
          project_id: 'proj-acme-001',
          summary: 'Approve delivery package for ACME analytics runtime.',
          recommendation: 'Approve after verifying client export blocker is cleared.',
          risks: ['Client export may arrive later than current delivery window.'],
          options: ['approve', 'reject', 'revise'],
          artifact_ref: 'projects/acme/proj-acme-001/deliverable-v1/',
        },
      ],
      messages: [],
      jobs: [],
    },
  ],
  health: {
    status: 'ready',
    uptime_seconds: 14400,
    active_tasks: 4,
    last_activity_timestamp: now,
  },
  readiness: {
    status: 'ready',
    uptime_seconds: 14400,
    active_tasks: 4,
    last_activity_timestamp: now,
    ready: true,
    registry_connected: true,
    recovery_loaded: true,
    lock_active: false,
    monitoring_cadence_minutes: 5,
    reasons: [],
    checklist: [
      'Bun installed and available on PATH.',
      'APP_PORT is free for the HTTP server.',
      'AI_API_KEY is configured for provider calls.',
    ],
  },
  runtime: {
    runtime_id: 'runtime-dev-01',
    mode: 'local',
    shell_status: 'running',
    workers: [
      {
        worker_id: 'worker-ceo',
        agent_id: 'ceo-agent',
        agent_type: 'ceo_agent',
        status: 'ready',
      },
      {
        worker_id: 'worker-engineering',
        agent_id: 'engineering-agent',
        agent_type: 'engineering_agent',
        status: 'busy',
        project_id: 'proj-acme-001',
      },
    ],
    started_at: '2026-05-15T23:00:00.000Z',
  },
  environment: {
    env: 'development',
    port: 3000,
    ai_base_url: 'http://127.0.0.1:8045/v1',
    ai_model: 'gemini-3-flash',
    ai_api_key_masked: 'sk-...mock',
  },
  extensions: [
    {
      id: 'skill-registry',
      kind: 'skill_registry',
      description: 'Local operator skill registry.',
      defaultEnabled: true,
      enabled: true,
      status: 'enabled',
      riskProfile: 'low',
      requiredEnv: [],
      optionalEnv: [],
      issues: [],
      config: {
        root: 'skills/',
      },
    },
  ],
}
